export const tiposToken = [
  { regex: /^num/, token: "PalabraReservadaNum" },
  { regex: /^string/, token: "PalabraReservadaString" },
  { regex: /^float/, token: "PalabraReservadaFloat" },
  { regex: /^function/, token: "PalabraReservadaFunction" },
  { regex: /^if/, token: "PalabraReservadaIf" },
  { regex: /^else/, token: "PalabraReservadaElse" },
  { regex: /^while/, token: "PalabraReservadaWhile" },
  { regex: /^for/, token: "PalabraReservadaFor" },
  { regex: /^print/, token: "PalabraReservadaPrint" },
  { regex: /^call/, token: "PalabraReservadaLlamadaFuncion" },
  { regex: /^[_a-zA-Z][_a-zA-Z0-9]*/, token: "Identificador" },
  { regex: /^"[^"]*"/, token: "Cadena" },
  { regex: /^-?[0-9]+(?:\.[0-9]+)?/, token: "Numero" },
  { regex: /^==/, token: "Igualdad" },
  { regex: /^=/, token: "Asignacion" },
  { regex: /^;/, token: "PuntoYComa" },
  { regex: /^{/, token: "LlaveApertura" },
  { regex: /^}/, token: "LlaveCierre" },
  { regex: /^\(/, token: "ParentesisApertura" },
  { regex: /^\)/, token: "ParentesisCierre" },
];
